### ISSUE TITLE
2nd rotary encoder

### ISSUE THREAD

**Issue by robvoi** [GitJer/Some_RPI-Pico_stuff#10]
Your solution for reading a rotary encoder works great.
I would like to use it for my robot. There I need a 2nd encoder.

I tried to initialize a 2nd one but don't get it to work. Whatever I try, even serial doesn't come up.

First I tried:
RotaryEncoder my_encoder(2);
RotaryEncoder my_encoder2(4);

I also tried top copy the class and put the 2nd encoder on PIO1 or SM2. Don't get it to work.

Do you have a tip on how to get a 2nd encoder to work? Thanks!

**Comment by GitJer** [comment]
Looking at my code from almost a year ago, I can see why it suggests that more than one encoder can be used, but it probably can't. Sorry for that!
There may be some problems:
- pio0 and sm=0 are hard coded, you already noticed that.
- the code uses interrupts. This is the main problem I think. The second encoder should use irq 2 and 3 in both the cpp and the pio code. That means that the second encoder would require the use of pio1 because the memory of the pio is not large enough to fit two programs (one with irq 0 and 1, and one with irq 2 and 3).

I'm not sure if there are other issues as well. 
Hope this helps. I haven't got my rpi pico set up right now, but if you run into problems, let me know. Then I'll get my pico ready to do some testing.

**Comment by robvoi** [comment]
Great. This worked!
Thanks for taking the time for your explanation.

Do you think there is a practical advantage using the PIOs over doing everything in main code like in this example: https://www.reddit.com/r/raspberrypipico/comments/pacarb/sharing_some_c_code_to_read_a_rotary_encoder/

**Comment by GitJer** [comment]
Good to hear it worked!

When I learned about the PIOs I immediately wanted to play with them just to see how far I can push them. In my examples I surely went overboard with e.g. the multiplication! 
I do think there is a very big advantage of letting a state machine handle I/O protocols: the CPUs can do their thing while state machines can handle IO very quickly (probably much quicker than compiled C-code, let alone micropython) and notify the main code that data has arrived / has been sent.

**Comment by robvoi** [comment]
Again, thanks for your time and the explanations.
